spring.application.name=students
server.port=8080

#Database
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/school
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl